### PR TITLE
Generate OpenAPI response documentation

### PR DESCRIPTION
**Pull request by werwty**

### CODE REVIEW

**Comment by werwty** [comment]
@unaguil 
Hello! Can you leave some feedback on this PR? I would love to get it merged so I can start using sphinx-swaggerdoc, and would be happy to make whatever changes you think is necessary.

**Comment by unaguil** [comment]
Hi @werwty,

Thank you very much for your contribution. I currently checking the functionality and I will integrate it as soon as possible.

**Comment by unaguil** [comment]
Hi again @werwty,

It seems that your code does not correctly process the following example from Swagger (http://petstore.swagger.io/v2/swagger.json). I need to check the Swagger specification but it appears that 'responses' do not always include an 'schema' property, however, expected by your code.

**Comment by werwty** [comment]
@unaguil I've pushed a new commit, schema and schema properties are optional and the properties table will only be displayed when it is provided.

**Comment by tuffnatty** [comment]
@werwty @unaguil There is also some work done [here](https://github.com/galthaus/sphinx-swaggerdoc/commit/f6f4c8c5fb58bfcf301be15290e722e157699d33) on this issue; not sure if the author is going to submit a PR but the code may have something useful.

**Comment by unaguil** [comment]
Thank you for your contribution @werwty

**Pull request merged**
